---
title: "Manuscript"
author: "Jesper Fischer Ehmsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, osfr, lmerTest, MuMIn, DHARMa, here, cmdstanr, tidybayes, bayesplot, posterior,future,furrr, patchwork, R.utils, brms, extraDistr)

scripts = c("agent.R","parameter_recovery.R","stan_functions.R","utility functions.R", "model recovery.R")
q = lapply(here("scripts", scripts), source)
```

## R Markdown



```{r parameters visualization}


```


```{r parameter recovery for RW}
mu_alpha = seq(0.1,0.5,by = 0.1)
kappa_alpha = seq(10,300,length.out = 3)

mu_w1 = seq(0.1,0.5,by = 0.1)
kappa_w1 = seq(10,300,length.out = 3)

sd_precision_percept = seq(0.1,2, length.out = 3)

sd_beta = seq(0.1,2, length.out = 3)

nsubs = 50

parameters = expand.grid(mu_alpha = mu_alpha,
                         kappa_alpha = kappa_alpha,
                         mu_w1 = mu_w1,
                         kappa_w1 = kappa_w1,
                         sd_precision_percept = sd_precision_percept,
                         sd_beta = sd_beta,
                         nsubs = nsubs)

parameters$id = 1:nrow(parameters)

data_list <- split(parameters, parameters$id)

plan(multisession, workers = availableCores()-1)

data_list = data_list[1:100]

rw_pp = furrr::future_map(data_list, ~parameter_recovery_rw(.x), .progress = TRUE, .options = furrr_options(seed = 123))
```



```{r parameter recovery for WB}

mu_alpha = seq(0.1,0.5,by = 0.1)
kappa_alpha = seq(10,300, length.out = 3)

mu_w1 = seq(0.1,0.5,by = 0.1)
kappa_w1 = seq(10,300, length.out = 3)

mu_w2 = seq(0.3,0.3,by = 0.1)
kappa_w2 = seq(10,300, length.out = 3)

sd_percept_precision = seq(0.1,2, length.out = 3)

sd_beta = seq(0.1,2, length.out = 3)


nsubs = 50

parameters = expand.grid(nsubs = nsubs, 
                         mu_alpha = mu_alpha, 
                         kappa_alpha = kappa_alpha, 
                         mu_w1 =  mu_w1, kappa_w1 = kappa_w1,
                         mu_w2 = mu_w2, kappa_w2 = kappa_w2, 
                         sd_percept_precision = sd_percept_precision, 
                         sd_beta = sd_beta)

parameters$id = 1:nrow(parameters)

data_list <- split(parameters, parameters$id)


plan(multisession, workers = availableCores()-1)

data_list = data_list[1:100]

wb_pp = furrr::future_map(data_list, ~parameter_recovery_wb(.x), .progress = TRUE, .options = furrr_options(seed = 123))


```




```{r parameter recovery for Kalman}


mu_sigmaEta = seq(1,100,length.out = 3)
mu_sigmaPsi = seq(1,100,length.out = 3)
mu_sigmaEpsilon = seq(1,100,length.out = 3)


sd_sigmaEta = seq(0.1,10,length.out = 3)
sd_sigmaPsi = seq(0.1,10,length.out = 3)
sd_sigmaEpsilon = seq(0.1,10,length.out = 3)


nsubs = 50

parameters = expand.grid(mu_sigmaEta = mu_sigmaEta,
                         mu_sigmaPsi = mu_sigmaPsi,
                         mu_sigmaEpsilon = mu_sigmaEpsilon,
                         sd_sigmaEta = sd_sigmaEta,
                         sd_sigmaPsi = sd_sigmaPsi,
                         sd_sigmaEpsilon = sd_sigmaEpsilon,
                         nsubs = nsubs)

parameters$id = 1:nrow(parameters)

data_list <- split(parameters, parameters$id)



plan(multisession, workers = availableCores()-1)



data_list = data_list[1:100]

kalman_pp = furrr::future_map(data_list, ~parameter_recovery_kalman(.x), .progress = TRUE, .options = furrr_options(seed = 123))


```



```{r}
#plot parameterrecovery
hier_pp <- do.call(rbind, lapply(rw_dd, "[[", 1))
hier_pp %>% mutate(divergences = ifelse(div > 0,1,0)) %>% 
  ggplot(aes(x = mean, y = reals.reals))+
  geom_point(aes(col = as.factor(divergences)))+
  facet_wrap(~variable, scales = "free")+
  theme_classic()+
  geom_abline(slope = 1, intercept = 0)+
  scale_color_manual("divergence?",values = c("black","red"))



sub_pp <- do.call(rbind, lapply(rw_dd, "[[", 2))
sub_pp %>% mutate(divergences = ifelse(div > 0,1,0)) %>% 
  ggplot(aes(x = mean, y = reals.reals))+
  geom_point(aes(col = as.factor(divergences)))+
  facet_wrap(~variable, scales = "free")+
  theme_classic()+
  geom_abline(slope = 1, intercept = 0)+
  scale_color_manual("divergence?",values = c("black","red"))


```


```{r model recovery}
########################################### Resorla wagner parameters:
mu_alpha = seq(0.1,0.3,length.out = 10)
kappa_alpha = 50
mu_w1 = seq(0.1,0.3,length.out = 10)
kappa_w1 = 50
sd_precision_percept = 0.5
sd_beta = 0.5
nsubs = 10
parameters = expand.grid(mu_alpha = mu_alpha,
                         kappa_alpha = kappa_alpha,
                         mu_w1 = mu_w1,
                         kappa_w1 = kappa_w1,
                         sd_precision_percept = sd_precision_percept,
                         sd_beta = sd_beta,
                         nsubs = nsubs)

parameters$id = 1:nrow(parameters)
data_list_rw <- split(parameters, parameters$id)

######################################## Weighted bayes

mu_alpha = rep(0.2,100)
kappa_alpha = 50
mu_w1 = 0.2
kappa_w1 = 50
mu_w2 = 0.2
kappa_w2 = 50
sd_percept_precision = 0.5
sd_beta = 0.5
nsubs = 10
parameters = expand.grid(nsubs = nsubs, 
                         mu_alpha = mu_alpha, 
                         kappa_alpha = kappa_alpha, 
                         mu_w1 =  mu_w1, kappa_w1 = kappa_w1,
                         mu_w2 = mu_w2, kappa_w2 = kappa_w2, 
                         sd_percept_precision = sd_percept_precision, 
                         sd_beta = sd_beta)
parameters$id = 1:nrow(parameters)
data_list_wb <- split(parameters, parameters$id)

######################################### Kalman

mu_sigmaEta = rep(0.1,100)
mu_sigmaPsi = 0.1
mu_sigmaEpsilon = 2
sd_sigmaEta = 0.1
sd_sigmaPsi = 0.1
sd_sigmaEpsilon = 0.1
nsubs = 10
parameters = expand.grid(mu_sigmaEta = mu_sigmaEta,
                         mu_sigmaPsi = mu_sigmaPsi,
                         mu_sigmaEpsilon = mu_sigmaEpsilon,
                         sd_sigmaEta = sd_sigmaEta,
                         sd_sigmaPsi = sd_sigmaPsi,
                         sd_sigmaEpsilon = sd_sigmaEpsilon,
                         nsubs = nsubs)
parameters$id = 1:nrow(parameters)
data_list_kalman <- split(parameters, parameters$id)


######################################### fit data_rw:
#loos = model_fitter_rwdata(data_list_rw[[1]])

data_list = data_list_rw[1:5]

plan(multisession, workers = 5)

rw_loo = furrr::future_map(data_list, ~model_fitter_rwdata(.x), .progress = TRUE, .options = furrr_options(seed = 123))

elpld_loo <- map_dfr(rw_loo, ~ .x[[1]])

full_loo <- map_dfr(rw_loo, ~ .x[[2]])



########################################## fit data_wb

data_list = data_list_wb[1]

plan(multisession, workers = 5)

wb_loo = furrr::future_map(data_list, ~model_fitter_wbdata(.x), .progress = TRUE, .options = furrr_options(seed = 123))


elpld_loo <- map_dfr(wb_loo, ~ .x[[1]])

full_loo <- map_dfr(wb_loo, ~ .x[[2]])



########################################### fit kalman data


data_list = data_list_kalman[1]

plan(multisession, workers = 5)

kalman_loo = furrr::future_map(data_list, ~model_fitter_kalmandata(.x), .progress = TRUE, .options = furrr_options(seed = 123))


elpld_loo <- map_dfr(kalman_loo, ~ .x[[1]])

full_loo <- map_dfr(kalman_loo, ~ .x[[2]])

```




```{r fitting RW model to session 1}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))

#ratings
df %>% filter(session == 2) %>% ggplot(aes(x = percept, fill = as.factor(stim))) + geom_histogram()
#cue-contingency
df %>% filter(session == 1, id == 1) %>% ggplot(aes(x = trial, y = u)) + geom_point()+theme_classic()


df = df %>% filter(session == 1)

#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)))


mod = cmdstan_model(here::here("Stan","myRW_real.stan"))

rw_fit_sess1 <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )
```


```{r fitting RW model to session 2}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))

#ratings
df %>% filter(session == 2) %>% ggplot(aes(x = percept, fill = as.factor(stim))) + geom_histogram()
#cue-contingency
df %>% filter(session == 1, id == 1) %>% ggplot(aes(x = trial, y = u)) + geom_point()+theme_classic()


df = df %>% filter(session == 2)

#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)))


mod = cmdstan_model(here::here("Stan","myRW_real.stan"))

rw_fit_sess2 <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )
```


```{r fitting Kalman model to session 1}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))


df = df %>% filter(session == 1)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL))
            )


mod = cmdstan_model(here::here("Stan","myKalmanfilter.stan"))

kalman_fit_sess1 <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )
```


```{r fitting Kalman model to session 2}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))


df = df %>% filter(session == 2)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL))
            )


mod = cmdstan_model(here::here("Stan","myKalmanfilter.stan"))

kalman_fit_sess1 <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )
```


```{r fitting WB model to session 1}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))



df = df %>% filter(session == 1)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(c(percept,stim), ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cue = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL))
            )


mod = cmdstan_model(here::here("Stan","hier_weighted_bayes.stan"))

fit <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )
```


```{r fitting WB model to session 2}

df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))



df = df %>% filter(session == 2)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(c(percept,stim), ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cue = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL))
            )


mod = cmdstan_model(here::here("Stan","hier_weighted_bayes.stan"))

fit <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )

```




















<!-- ```{r hierachical session correlation} -->


<!-- df= read.csv(here::here("data_TPL_AC.csv")) %>% -->
<!--   rename_all(tolower) %>% -->
<!--   filter(trial != 0) %>% -->
<!--   rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% -->
<!--   mutate_all(replace_na, 0) %>% mutate(id = as.factor(id), trial = as.factor(trial), session = as.factor(session)) -->

<!-- df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0)) -->
<!-- df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0)) -->



<!-- #ratings -->
<!-- df %>% filter(session == 2) %>% ggplot(aes(x = percept, fill = as.factor(stim))) + geom_histogram() -->
<!-- #cue-contingency -->
<!-- df %>% filter(session == 1, id == 1) %>% ggplot(aes(x = trial, y = u)) + geom_point()+theme_classic() -->


<!-- #fitting hierachically -->
<!-- data = df %>% mutate(percept = percept/100) -->



<!-- data = data %>% mutate(across(percept, ~case_when( -->
<!--     . < 0.001 ~ 0.001, -->
<!--     . > 0.999 ~ 0.999, -->
<!--     TRUE ~ . -->
<!--   ))) -->


<!-- data1 = list(nsubs = length(unique(data$id)), -->
<!--             ntrials = nrow(data %>% filter(session == 1) %>% filter(id %in% unique(id)[1])), -->
<!--             sesions = length(unique(data$session)), -->
<!--             percept = get_3darray(data,variable = "percept"), -->
<!--             expectPain = get_3darray(data,variable = "pred"), -->
<!--             percept_bin = get_3darray(data,variable = "percept_bin"), -->
<!--             stim = get_3darray(data,variable = "stim"), -->
<!--             cues = get_3darray(data,variable = "cue"), -->
<!--             u = get_3darray(data,variable = "u") -->
<!--             ) -->


<!-- mod = cmdstan_model(here::here("Stan","fitting both sessions","myRW_correlation.stan")) -->


<!-- fit <- mod$sample( -->
<!--   data = data1, -->
<!--   chains = 4, -->
<!--   parallel_chains = 4, -->
<!--   refresh = 100, -->
<!--   adapt_delta = 0.90, -->
<!--   max_treedepth = 12 -->
<!-- ) -->



<!-- sum = fit$summary(variables = c("mu_alpha","mu_w1","sd_beta","sd_precision_percept", "kappa_alpha","kappa_w1","alpha","w1","beta","precision_percept")) -->

<!-- variabless = c("mu_alpha[1]","mu_w1[1]","sd_beta[1]","sd_precision_percept[1]","mu_alpha[2]","mu_w1[2]","sd_beta[2]","sd_precision_percept[2]") -->

<!-- pairs = mcmc_pairs(fit$draws(variables = variabless), np = nuts_params(fit), pars = variabless, -->
<!--                    off_diag_args = list(size = 0.75)) -->
<!-- ``` -->




<!-- ```{r fitting to real data tester hierachical RW session 1} -->

<!-- df= read.csv(here::here("data_TPL_AC.csv")) %>%  -->
<!--   rename_all(tolower) %>%  -->
<!--   filter(trial != 0) %>%  -->
<!--   rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%  -->
<!--   mutate_all(replace_na, 0) -->

<!-- df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0)) -->
<!-- df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0)) -->



<!-- #ratings -->
<!-- df %>% filter(session == 2) %>% ggplot(aes(x = percept, fill = as.factor(stim))) + geom_histogram() -->
<!-- #cue-contingency -->
<!-- df %>% filter(session == 1, id == 1) %>% ggplot(aes(x = trial, y = u)) + geom_point()+theme_classic() -->


<!-- df = df %>% filter(session == 1) -->


<!-- source(here::here("stan_functions.R")) -->
<!-- #fitting hierachically -->
<!-- data = df %>% mutate(percept = percept/100) -->



<!-- data = data %>% mutate(across(percept, ~case_when( -->
<!--     . < 0.001 ~ 0.001, -->
<!--     . > 0.999 ~ 0.999, -->
<!--     TRUE ~ . -->
<!--   ))) -->


<!-- data1 = list(nsubs = length(unique(data$id)), -->
<!--             ntrials = nrow(data %>% filter(id %in% unique(id)[1])), -->
<!--             percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)), -->
<!--             expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)), -->
<!--             percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)), -->
<!--             stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)), -->
<!--             cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)), -->
<!--             u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)) -->
<!--             ) -->

<!-- data1 = list(nsubs = length(unique(data$id)), -->
<!--             ntrials = nrow(data %>% filter(id %in% unique(id)[1])), -->
<!--             pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)), -->
<!--             u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)) -->
<!--             ) -->





<!-- mod = cmdstan_model(here::here("Stan","rw_vs_rw_hier.stan")) -->

<!-- rw_fit_ses1 <- mod$sample( -->
<!--       data = data1, -->
<!--       chains = 4,  -->
<!--       parallel_chains = 4, -->
<!--       refresh = 100, -->
<!--       adapt_delta = 0.90, -->
<!--       max_treedepth = 12 -->
<!--     ) -->
<!-- ``` -->



<!-- ```{r fitting to real data tester hierachical RW seesion2} -->

<!-- df= read.csv(here::here("data_TPL_AC.csv")) %>%  -->
<!--   rename_all(tolower) %>%  -->
<!--   filter(trial != 0) %>%  -->
<!--   rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%  -->
<!--   mutate_all(replace_na, 0) -->

<!-- df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0)) -->
<!-- df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0)) -->



<!-- #ratings -->
<!-- df %>% filter(session == 2) %>% ggplot(aes(x = percept, fill = as.factor(stim))) + geom_histogram() -->
<!-- #cue-contingency -->
<!-- df %>% filter(session == 1, id == 1) %>% ggplot(aes(x = trial, y = u)) + geom_point()+theme_classic() -->


<!-- df = df %>% filter(session == 2) -->


<!-- source(here::here("stan_functions.R")) -->
<!-- #fitting hierachically -->
<!-- data = df %>% mutate(percept = percept/100) -->



<!-- data = data %>% mutate(across(percept, ~case_when( -->
<!--     . < 0.001 ~ 0.001, -->
<!--     . > 0.999 ~ 0.999, -->
<!--     TRUE ~ . -->
<!--   ))) -->


<!-- data1 = list(nsubs = length(unique(data$id)), -->
<!--             ntrials = nrow(data %>% filter(id %in% unique(id)[1])), -->
<!--             percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)), -->
<!--             expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)), -->
<!--             percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)), -->
<!--             stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)), -->
<!--             cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)), -->
<!--             u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)) -->
<!--             ) -->

<!-- data1 = list(nsubs = length(unique(data$id)), -->
<!--             ntrials = nrow(data %>% filter(id %in% unique(id)[1])), -->
<!--             pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)), -->
<!--             u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)) -->
<!--             ) -->





<!-- mod = cmdstan_model(here::here("Stan","rw_vs_rw_hier.stan")) -->

<!-- rw_fit_ses2 <- mod$sample( -->
<!--       data = data1, -->
<!--       chains = 4,  -->
<!--       parallel_chains = 4, -->
<!--       refresh = 100, -->
<!--       adapt_delta = 0.90, -->
<!--       max_treedepth = 12 -->
<!--     ) -->
<!-- ``` -->


