---
title: "Manuscript"
author: "Jesper Fischer Ehmsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, osfr, lmerTest, MuMIn, DHARMa, here, cmdstanr, tidybayes, bayesplot, posterior,future,furrr, patchwork, R.utils, brms, extraDistr,cowplot)

scripts = c("agent.R","parameter_recovery.R","stan_functions.R","utility functions.R", "model recovery.R","visualize_parameters.R")
q = lapply(here("scripts", scripts), source)
```

## R Markdown



```{r parameters visualization, fig.height=10, fig.width=12}
dd = get_experiment()

rwplot = RW(dd)

kalmanplot = KALMAN_v2(dd)

wbplot = WB(dd)

layout = (c(
  area(1, 1),
  area(1, 2),
  area(2, 1),
  area(2, 2)
  
))


  
trial_struc = ggdraw() +
  draw_image(magick::image_read(here::here("figures", "main-experiment.PNG")), scale = 1.5)

trial_struc+kalmanplot+rwplot+wbplot+plot_layout(design = layout)+plot_annotation(tag_levels = 'A')



#RW_logistic = RW_logistic_vis(dd)
```


```{r parameter recovery for RW}
mu_alpha = seq(0.1,0.5,by = 0.1)
kappa_alpha = seq(10,300,length.out = 3)

mu_w1 = seq(0.1,0.5,by = 0.1)
kappa_w1 = seq(10,300,length.out = 3)

sd_precision_percept = seq(0.1,2, length.out = 3)

sd_beta = seq(0.1,2, length.out = 3)

nsubs = 10

parameters = expand.grid(mu_alpha = mu_alpha,
                         kappa_alpha = kappa_alpha,
                         mu_w1 = mu_w1,
                         kappa_w1 = kappa_w1,
                         sd_precision_percept = sd_precision_percept,
                         sd_beta = sd_beta,
                         nsubs = nsubs)

parameters$id = 1:nrow(parameters)

data_list <- split(parameters, parameters$id)

plan(multisession, workers = 3)

data_list1 = data_list[501:600]

rw_pp = furrr::future_map(data_list, ~parameter_recovery_rw(.x), .progress = TRUE, .options = furrr_options(seed = 123))





```



```{r parameter recovery for WB}

mu_alpha = seq(0.1,0.5,by = 0.1)
kappa_alpha = seq(10,300, length.out = 3)

mu_w1 = seq(0.1,0.5,by = 0.1)
kappa_w1 = seq(10,300, length.out = 3)

mu_w2 = seq(0.3,0.3,by = 0.1)
kappa_w2 = seq(10,300, length.out = 3)

sd_percept_precision = seq(0.1,2, length.out = 3)

sd_beta = seq(0.1,2, length.out = 3)


nsubs = 50

parameters = expand.grid(nsubs = nsubs, 
                         mu_alpha = mu_alpha, 
                         kappa_alpha = kappa_alpha, 
                         mu_w1 =  mu_w1, kappa_w1 = kappa_w1,
                         mu_w2 = mu_w2, kappa_w2 = kappa_w2, 
                         sd_percept_precision = sd_percept_precision, 
                         sd_beta = sd_beta)

parameters$id = 1:nrow(parameters)

data_list <- split(parameters, parameters$id)


plan(multisession, workers = availableCores()-1)

data_list = data_list[1:100]

wb_pp = furrr::future_map(data_list, ~parameter_recovery_wb(.x), .progress = TRUE, .options = furrr_options(seed = 123))


```




```{r parameter recovery for Kalman}


mu_sigmaEta = seq(0.1,1,length.out = 3)
mu_sigmaPsi = seq(0.1,5,length.out = 3)
mu_sigmaEpsilon = seq(0.1,5,length.out = 3)


sd_sigmaEta = seq(0.1,1,length.out = 2)
sd_sigmaPsi = seq(0.1,1,length.out = 2)
sd_sigmaEpsilon = seq(0.1,1,length.out = 2)

sd_precision_percept = seq(0.1,1, length.out = 2)

sd_beta = seq(0.1,1, length.out = 2)



nsubs = 10

parameters = expand.grid(mu_sigmaEta = mu_sigmaEta,
                         mu_sigmaPsi = mu_sigmaPsi,
                         mu_sigmaEpsilon = mu_sigmaEpsilon,
                         sd_sigmaEta = sd_sigmaEta,
                         sd_sigmaPsi = sd_sigmaPsi,
                         sd_sigmaEpsilon = sd_sigmaEpsilon,
                         sd_precision_percept = sd_precision_percept, 
                         sd_beta = sd_beta,
                         nsubs = nsubs)

parameters$id = 1:nrow(parameters)

data_list <- split(parameters, parameters$id)



#plan(multisession, workers = availableCores()-1)


data_list = data_list[1:2]

kalman_pp = furrr::future_map(data_list, ~parameter_recovery_kalman(.x), .progress = TRUE, .options = furrr_options(seed = 123))


```



```{r parameter recovery for logistic}
mu_alpha = seq(0.1,0.5, length.out = 5)
kappa_alpha = seq(10,100, length.out = 2)

mu_b0 = -1.5
sd_b0 = 0.5

mu_b1 = seq(0.1,2,length.out = 5)
sd_b1 = seq(0.1,2,length.out = 3)

mu_b2 = seq(0.1,2,length.out = 5)
sd_b2 = seq(0.1,2,length.out = 3)


mu_b0_b = -4
sd_b0_b = 0.5

mu_b1_b = 7
sd_b1_b = 0.5

mu_b2_b = 0.7
sd_b2_b = 0.5

sd_percept_precision = 0.8

nsubs = 10

parameters = expand.grid(mu_alpha = mu_alpha,
                         kappa_alpha = kappa_alpha,
                         mu_b0 = mu_b0,
                         sd_b0 = sd_b0,
                         mu_b1 = mu_b1,
                         sd_b1 = sd_b1,
                         mu_b2 = mu_b2,
                         sd_b2 = sd_b2,
                         mu_b0_b = mu_b0_b,
                         sd_b0_b = sd_b0_b,
                         mu_b1_b = mu_b1_b,
                         sd_b1_b = sd_b1_b,
                         mu_b2_b = mu_b2_b,
                         sd_b2_b = sd_b2_b,
                         sd_percept_precision = sd_percept_precision,
                         nsubs = nsubs)



parameters$id = 1:nrow(parameters)

data_list <- split(parameters, parameters$id)

plan(multisession, workers = 5)


rw_pp = furrr::future_map(data_list, ~parameter_recovery_logistic_rw(.x), .progress = TRUE, .options = furrr_options(seed = 123))


```



```{r}

files = paste0(here::here("workspace","parameterrecovery"),"/",list.files(here::here("workspace","parameterrecovery")))


#plot parameterrecovery
load(files[[2]])
q = lapply(here("scripts", scripts), source)
rwplot = plot_parameterrecovery(rw_pp, div = T, subs = 5)
load(files[[3]])
q = lapply(here("scripts", scripts), source)
wbplot = plot_parameterrecovery(wb_pp, div = T, subs = 5)
load(files[[1]])
q = lapply(here("scripts", scripts), source)
kalmanplot = plot_parameterrecovery(kalman_pp, div = T, subs = 5)

layout = (c(
  area(1, 1, 2,3),
  area(3, 1,5,3),
  area(6, 1,6,3)
  
))

plot(layout)

((rwplot[[1]]+wbplot[[1]]+kalmanplot[[1]])/(rwplot[[2]]+wbplot[[2]]+kalmanplot[[2]])/((rwplot[[3]]+wbplot[[3]]+kalmanplot[[3]])))+
  plot_annotation(tag_levels = 'A')+
  plot_layout(design = layout,guides = 'collect')

```


```{r model recovery}
########################################### Resorla wagner parameters:
mu_alpha = rep(0.3,100)
kappa_alpha = 50
mu_w1 = rep(0.3,100)
kappa_w1 = 50
sd_precision_percept = 0.5
sd_beta = 0.5
nsubs = 10
parameters = expand.grid(mu_alpha = mu_alpha,
                         kappa_alpha = kappa_alpha,
                         mu_w1 = mu_w1,
                         kappa_w1 = kappa_w1,
                         sd_precision_percept = sd_precision_percept,
                         sd_beta = sd_beta,
                         nsubs = nsubs)

parameters$id = 1:nrow(parameters)
data_list_rw <- split(parameters, parameters$id)

######################################## Weighted bayes

mu_alpha = rep(0.2,100)
kappa_alpha = 50
mu_w1 = 0.2
kappa_w1 = 50
mu_w2 = 0.2
kappa_w2 = 50
sd_percept_precision = 0.5
sd_beta = 0.5
nsubs = 10
parameters = expand.grid(nsubs = nsubs, 
                         mu_alpha = mu_alpha, 
                         kappa_alpha = kappa_alpha, 
                         mu_w1 =  mu_w1, kappa_w1 = kappa_w1,
                         mu_w2 = mu_w2, kappa_w2 = kappa_w2, 
                         sd_percept_precision = sd_percept_precision, 
                         sd_beta = sd_beta)
parameters$id = 1:nrow(parameters)
data_list_wb <- split(parameters, parameters$id)

######################################### logistic RW




######################################### fit data_rw:
#loos = model_fitter_rwdata(data_list_rw[[1]])

data_list = data_list_rw[1:5]

plan(multisession, workers = 5)

rw_loo = furrr::future_map(data_list, ~model_fitter_rwdata(.x), .progress = TRUE, .options = furrr_options(seed = 123))

elpld_loo <- map_dfr(rw_loo, ~ .x[[1]])

full_loo <- map_dfr(rw_loo, ~ .x[[2]])



########################################## fit data_wb

data_list = data_list_wb[1:100]

plan(multisession, workers = 10)

wb_loo = furrr::future_map(data_list, ~model_fitter_wbdata(.x), .progress = TRUE, .options = furrr_options(seed = 123))


elpld_loo <- map_dfr(wb_loo, ~ .x[[1]])

full_loo <- map_dfr(wb_loo, ~ .x[[2]])



########################################### fit kalman data


data_list = data_list_kalman[1]

plan(multisession, workers = 5)

kalman_loo = furrr::future_map(data_list, ~model_fitter_kalmandata(.x), .progress = TRUE, .options = furrr_options(seed = 123))


elpld_loo <- map_dfr(kalman_loo, ~ .x[[1]])

full_loo <- map_dfr(kalman_loo, ~ .x[[2]])

```



```{r model recovery table:}

get_value = function(loo){
  get_from_means <- do.call(rbind, lapply(loo, "[[", 1))

  get_from_means$id = as.factor(get_from_means$id)
# Group by ID and find the model with the minimum value
  min_values <- get_from_means %>%
  group_by(id) %>%
  filter(means == min(means))

# Count the occurrences of each model with the minimum value per run
  model_counts <- min_values %>%
    group_by(names) %>%
    summarize(Count = n())


  get_from_loo <- do.call(rbind, lapply(loo, "[[", 2))

  get_from_loo = get_from_loo %>% filter(elpd_diff == 0) %>% mutate(model = row.names(.)) %>% mutate(realmodel = sub("^[0-9]+\\.(.*)", "\\1", model)) %>% group_by(realmodel) %>% summarize(Count = n())

  return(list(fromloo = get_from_loo, frommean = model_counts))
}

get_value(rw_loo)
```




```{r fitting RW model to session 1}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))


df = df %>% filter(session == 1)

#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)))




mod = cmdstan_model(here::here("Stan","myRW_real.stan"))

rw_fit_sess1 <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )

ppu_hier(fit = rw_fit_sess1,
         parameters = c("alpha","w1","precision_percept"),
         reals = NA)

```


```{r plotting 1 agent}

percept = sum %>% filter(str_detect(variable, "painMu"))
percept = percept[1:160,]

expect = sum %>% filter(str_detect(variable, "expectMu"))
expect = expect[1:160,]

percept$stim = data$stim
percept$expect = expect$mean

percept %>% ggplot(aes(x=1:nrow(.), y = mean, col = as.factor(stim)))+geom_point()

percept %>% ggplot(aes(x=expect, y = mean, col = as.factor(stim)))+geom_point()



ass = sum %>% filter(str_detect(variable, "associ"))
ass = ass[1:161,]

ass %>% ggplot(aes(x=1:nrow(.), y = mean))+geom_line()+geom_point(data = data, aes(x = trial, y = u))


rw_fit_sess1$diagnostic_summary()

alpha = get_diag(rw_fit_sess1, "alpha")
w1 = get_diag(rw_fit_sess1, "w1")
pp = get_diag(rw_fit_sess1, "precision_percept")
beta = get_diag(rw_fit_sess1, "beta")

```


```{r fitting RW model to session 2}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))



df = df %>% filter(session == 2)

#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)))


mod = cmdstan_model(here::here("Stan","myRW_real.stan"))

rw_fit_sess2 <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )

ppu_hier(fit = rw_fit_sess2,
         parameters = c("alpha","w1","precision_percept"),
         reals = NA)



```


```{r fitting Kalman model to session 1}
df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))


df = df %>% filter(session == 1)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL))
            )

mod = cmdstan_model(here::here("Stan","myKalmanfilter_v3_nocent.stan"))

kalman_fit_sess1 <- mod$sample(
      data = data1,
      chains = 4,
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )


ppu_hier(fit = kalman_fit_sess1,
         parameters = c("sigmaEta","sigmaPsi","sigmaEpsilon","precision_percept"),
         reals = NA)


# 
# ppu_sub(fit = fit,
#         parameter = "precision_percept",
#         reals = df,
#         lims = -1,
#         lime = 10,
#         nsubs = NA
#         )

get_diag(kalman_fit_sess1, "sigmaEta")
get_diag(kalman_fit_sess1, "sigmaPsi")
get_diag(kalman_fit_sess1, "sigmaEpsilon")



sum = kalman_fit_sess1$summary()

ass = sum %>% filter(str_detect(variable, "perceptmuu"))
ass = ass[(161*2-1):(161*3-1),]

exp = sum %>% filter(str_detect(variable, "exp_muu"))
exp = exp[(161*2-1):(161*3-1),]


ass$exp = exp$mean

ass %>% ggplot(aes(x=exp, y = mean))+geom_point()

```


```{r fitting Kalman model to session 2}
df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))


df = df %>% filter(session == 2)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL))
            )


mod = cmdstan_model(here::here("Stan","myKalmanfilter_v3_nocent.stan"))

kalman_fit_sess2 <- mod$sample(
      data = data1,
      chains = 4,
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )

ppu_hier(fit = kalman_fit_sess2,
         parameters = c("sigmaEta","sigmaPsi","sigmaEpsilon","precision_percept"),
         reals = NA)

```


```{r fitting WB model to session 1}
df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))



df = df %>% filter(session == 1)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(c(percept,stim), ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cue = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL))
            )


mod = cmdstan_model(here::here("Stan","hier_weighted_bayes.stan"))

wb_fit_sess1  <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )


wb_fit_sess1$diagnostic_summary()

alpha = get_diag(wb_fit_sess1, "alpha")
w1 = get_diag(wb_fit_sess1, "w1")
w2 = get_diag(wb_fit_sess1, "w2")
pp = get_diag(wb_fit_sess1, "percept_precision")
beta = get_diag(wb_fit_sess1, "beta")


```


```{r fitting WB model to session 2}

df= read.csv(here::here("data_TPL_AC.csv")) %>% 
  rename_all(tolower) %>% 
  filter(trial != 0) %>% 
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% 
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))



df = df %>% filter(session == 2)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(c(percept,stim), ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cue = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL))
            )


mod = cmdstan_model(here::here("Stan","hier_weighted_bayes.stan"))

wb_fit_sess2 <- mod$sample(
      data = data1,
      chains = 4, 
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )


alpha = get_diag(wb_fit_sess1, "alpha")
w1 = get_diag(wb_fit_sess1, "w1")
w2 = get_diag(wb_fit_sess1, "w2")
pp = get_diag(wb_fit_sess1, "percept_precision")
beta = get_diag(wb_fit_sess1, "beta")



```











```{r}
get_corplot(rw_fit_sess1, rw_fit_sess2, "alpha")
get_corplot(rw_fit_sess1, rw_fit_sess2, "w1")
get_corplot(rw_fit_sess1, rw_fit_sess2, "precision_percept")


get_corplot(wb_fit_sess1, wb_fit_sess2, "alpha")
get_corplot(wb_fit_sess1, wb_fit_sess2, "w1")
get_corplot(wb_fit_sess1, wb_fit_sess2, "w2")
get_corplot(wb_fit_sess1, wb_fit_sess2, "beta")
get_corplot(wb_fit_sess1, wb_fit_sess2, "percept_precision")


```









```{r}
df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))
df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0))



df = df %>% filter(session == 1)


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            expectPain = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL))
            )

mod = cmdstan_model(here::here("Stan","myKalmanfilter_v3_nocent.stan"))

kalman_fit_sess1 <- mod$sample(
      data = data1,
      chains = 4,
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )
```










```{r hierachical session correlation (RW)}


df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0) %>% mutate(id = as.factor(id), trial = as.factor(trial), session = as.factor(session))

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(session == 1) %>% filter(id %in% unique(id)[1])),
            sesions = length(unique(data$session)),
            percept = get_3darray(data,variable = "percept"),
            expectPain = get_3darray(data,variable = "pred"),
            percept_bin = get_3darray(data,variable = "percept_bin"),
            stim = get_3darray(data,variable = "stim"),
            cues = get_3darray(data,variable = "cue"),
            u = get_3darray(data,variable = "u")
            )


mod = cmdstan_model(here::here("Stan","fitting both sessions","myRW_real_both_sess.stan"))


fit <- mod$sample(
  data = data1,
  chains = 4,
  parallel_chains = 4,
  refresh = 100,
  adapt_delta = 0.90,
  max_treedepth = 12
)



sum = fit$summary(variables = c("mu_alpha","mu_w1","sd_beta","sd_precision_percept", "kappa_alpha","kappa_w1","alpha","w1","beta","precision_percept"))

variabless = c("mu_alpha[1]","mu_w1[1]","sd_beta[1]","sd_precision_percept[1]","mu_alpha[2]","mu_w1[2]","sd_beta[2]","sd_precision_percept[2]")

pairs = mcmc_pairs(fit$draws(variables = variabless), np = nuts_params(fit), pars = variabless,
                   off_diag_args = list(size = 0.75))

mcmc_trace(fit$draws(variables = "alpha"))

alpha = fit$summary(variables = "alpha")
w1 = fit$summary(variables = "w1")

alphas1 <- w1 %>%
  filter(grepl("1]$", variable))


alphas2 <- w1 %>%
  filter(grepl("2]$", variable))


cor.test(alphas1$mean, alphas2$mean)



correlation = as_draws_df(fit$draws(variables = "correlation_alpha"))
hist(correlation$correlation_alpha)
correlation = as_draws_df(fit$draws(variables = "correlation_w1"))
hist(correlation$correlation_w1)
```




```{r hierachical session correlation (WB)}

df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0) %>% mutate(id = as.factor(id), trial = as.factor(trial), session = as.factor(session))

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))




#fitting hierachically
data = df %>% mutate(percept = percept/100)


data = data %>% mutate(across(c(percept,stim), ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(session == 1) %>% filter(id %in% unique(id)[1])),
            sesions = length(unique(data$session)),
            percept = get_3darray(data,variable = "percept"),
            pred = get_3darray(data,variable = "pred"),
            percept_bin = get_3darray(data,variable = "percept_bin"),
            stim = get_3darray(data,variable = "stim"),
            cue = get_3darray(data,variable = "cue")
            )





mod = cmdstan_model(here::here("Stan","fitting both sessions","hier_weighted_bayes_correlation.stan"))


fit_wb_bs <- mod$sample(
  data = data1,
  chains = 4,
  parallel_chains = 4,
  refresh = 100,
  adapt_delta = 0.90,
  max_treedepth = 12
)



correlation = as_draws_df(fit_wb_bs$draws(variables = "correlation_alpha"))
hist(correlation$correlation_alpha)
correlation = as_draws_df(fit_wb_bs$draws(variables = "correlation_w1"))
hist(correlation$correlation_w1)
correlation = as_draws_df(fit_wb_bs$draws(variables = "correlation_w2"))
hist(correlation$correlation_w2)


```





```{r fitting to both sessions to hierachiacal RW}

df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))
df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0))



#source(here::here("stan_functions.R"))
#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(session == 1) %>% filter(id %in% unique(id)[1])),
            sessions = 2,
            pred = get_3darray(data,variable = "pred"),
            u = get_3darray(data,variable = "u")
            )





mod = cmdstan_model(here::here("Stan","rw_vs_rw_hier.stan"))

rw_fit_ses1 <- mod$sample(
      data = data1,
      chains = 4,
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )


sum = rw_fit_ses1$summary(variables = c("alpha", "mu_alpha","sd_alpha","mu_mu_alpha","sd_sd_alpha","mu_sd_alpha","sd_mu_alpha"))
```


```{r, fitting to real data tester hierachical RW sessions1}

df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))
df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0))


df = df %>% filter(session == 1)


#source(here::here("stan_functions.R"))
#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))




data2 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL))
            )




mod = cmdstan_model(here::here("Stan","rw_vs_rw_hier_complete.stan"))

rw_fit_ses1 <- mod$sample(
      data = data2,
      chains = 4,
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )


sum1 = rw_fit_ses1$summary()
```



```{r, fitting to real data tester hierachical RW sessions2}

df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0)

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))
df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0))


df = df %>% filter(session == 2)


#source(here::here("stan_functions.R"))
#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))




data2 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL))
            )




mod = cmdstan_model(here::here("Stan","rw_vs_rw_hier_complete.stan"))

rw_fit_ses2 <- mod$sample(
      data = data2,
      chains = 4,
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )


sum2 = rw_fit_ses2$summary()


get_corplot(rw_fit_ses1,rw_fit_ses2, "b2_b")
```



```{r}

df= read.csv(here::here("data_TPL_AC.csv")) %>%
  rename_all(tolower) %>%
  filter(trial != 0) %>%
  rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>%
  mutate_all(replace_na, 0) %>% mutate(id = as.factor(id), trial = as.factor(trial), session = as.factor(session))

df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0))
df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0))


#fitting hierachically
data = df %>% mutate(percept = percept/100)



data = data %>% mutate(across(percept, ~case_when(
    . < 0.001 ~ 0.001,
    . > 0.999 ~ 0.999,
    TRUE ~ .
  )))


data1 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(session == 1) %>% filter(id %in% unique(id)[1])),
            sesions = length(unique(data$session)),
            percept = get_3darray(data,variable = "percept"),
            pred = get_3darray(data,variable = "pred"),
            percept_bin = get_3darray(data,variable = "percept_bin"),
            stim = get_3darray(data,variable = "stim"),
            cues = get_3darray(data,variable = "cue"),
            u = get_3darray(data,variable = "u")
            )


mod = cmdstan_model(here::here("Stan","fitting both sessions","rw_vs_rw_hier_complete_both_sessions.stan"))


fit <- mod$sample(
  data = data1,
  chains = 4,
  parallel_chains = 4,
  refresh = 10,
  adapt_delta = 0.90,
  max_treedepth = 12
)


```



```{r}
mu_alpha = 0.3
kappa_alpha = 30

mu_b0 = -5
sd_b0 = 1

mu_b1 = -1
sd_b1 = 1

mu_b2 = 1.3
sd_b2 = 1.3


mu_b0_b = -5
sd_b0_b = 2

mu_b1_b = 0.5
sd_b1_b = 0.5

mu_b2_b = 0.5
sd_b2_b = 0.5

sd_percept_precision = 0.5

nsubs = 10

parameters = expand.grid(mu_alpha = mu_alpha,
                         kappa_alpha = kappa_alpha,
                         mu_b0 = mu_b0,
                         sd_b0 = sd_b0,
                         mu_b1 = mu_b1,
                         sd_b1 = sd_b1,
                         mu_b2 = mu_b2,
                         sd_b2 = sd_b2,
                         mu_b0_b = mu_b0_b,
                         sd_b0_b = sd_b0_b,
                         mu_b1_b = mu_b1_b,
                         sd_b1_b = sd_b1_b,
                         mu_b2_b = mu_b2_b,
                         sd_b2_b = sd_b2_b,
                         sd_percept_precision = sd_percept_precision,
                         nsubs = nsubs)


df = hier_rw_logistic(parameters)
    
data = df[[1]]


data2 = list(nsubs = length(unique(data$id)),
            ntrials = nrow(data %>% filter(id %in% unique(id)[1])),
            pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)),
            percept_bin = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept_bin)%>% mutate(trial= NULL)),
            percept = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = percept)%>% mutate(trial= NULL)),
            stim = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = stim)%>% mutate(trial= NULL)),
            u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)),
            cues = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = cue)%>% mutate(trial= NULL))
            )


hier = df[[2]]
df = df[[1]]

mod = cmdstan_model(here::here("Stan","rw_vs_rw_hier_complete.stan"))

fit <- mod$sample(
      data = data2,
      chains = 4,
      parallel_chains = 4,
      refresh = 100,
      adapt_delta = 0.90,
      max_treedepth = 12
    )

hier_parameters = c("mu_b0","mu_b1","mu_b2","sd_b0","sd_b1","sd_b2","mu_b0_b","mu_b1_b","mu_b2_b","sd_b0_b","sd_b1_b","sd_b2_b","kappa_alpha","mu_alpha","sd_percept_precision")

sub_parameters = c("b0","b1","b2","b0_b","b1_b","b2_b","alpha","percept_precision")

list(hier = data.frame(fit$summary(hier_parameters),
                                  reals = hier %>% dplyr::select(all_of(hier_parameters)) %>% pivot_longer(everything()) %>% rename(reals = value),
                                  div = sum(fit$diagnostic_summary()$num_divergent),index = index),
                sub = data.frame(fit$summary(sub_parameters) %>% arrange(variable),
                                 reals = df %>% filter(trial == 1) %>% mutate(ids = 1:nrow(.)) %>% dplyr::select(all_of(sub_parameters),ids) %>% 
                                 pivot_longer(cols = -ids) %>% rename(reals =value) %>% mutate(names = paste0(name,"[",ids,"]")) %>% arrange(names) %>% select(names,reals),
                                 div = sum(fit$diagnostic_summary()$num_divergent),index = index))



#sum = fit$summary()


```



<!-- ```{r fitting to real data tester hierachical RW seesion2} -->

<!-- df= read.csv(here::here("data_TPL_AC.csv")) %>% -->
<!--   rename_all(tolower) %>% -->
<!--   filter(trial != 0) %>% -->
<!--   rename(id = participant, stim = stimulus, percept = rating, pred = prediction, percept_bin = quality) %>% -->
<!--   mutate_all(replace_na, 0) -->

<!-- df$u = ifelse(df$cue == 1 & df$stim == 1, 1, ifelse(df$cue == 0 & df$stim == 0, 1,0)) -->
<!-- df$pred = ifelse(df$cue == 1 & df$pred == 1, 1, ifelse(df$cue == 0 & df$pred == 0, 1,0)) -->


<!-- df = df %>% filter(session == 2) -->


<!-- #source(here::here("stan_functions.R")) -->
<!-- #fitting hierachically -->
<!-- data = df %>% mutate(percept = percept/100) -->



<!-- data = data %>% mutate(across(percept, ~case_when( -->
<!--     . < 0.001 ~ 0.001, -->
<!--     . > 0.999 ~ 0.999, -->
<!--     TRUE ~ . -->
<!--   ))) -->




<!-- data2 = list(nsubs = length(unique(data$id)), -->
<!--             ntrials = nrow(data %>% filter(id %in% unique(id)[1])), -->
<!--             pred = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = pred)%>% mutate(trial= NULL)), -->
<!--             u = as.matrix(data %>% pivot_wider(id_cols = trial, names_from = id, values_from = u)%>% mutate(trial= NULL)) -->
<!--             ) -->





<!-- mod = cmdstan_model(here::here("Stan","rw_vs_rw_hier.stan")) -->

<!-- rw_fit_ses2 <- mod$sample( -->
<!--       data = data2, -->
<!--       chains = 4, -->
<!--       parallel_chains = 4, -->
<!--       refresh = 100, -->
<!--       adapt_delta = 0.90, -->
<!--       max_treedepth = 12 -->
<!--     ) -->



<!-- ``` -->


